# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0012_auto_20160927_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestiongroup',
            name='question_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questionnaires.QuestionGroup'),
        ),
        migrations.AddField(
            model_name='historicalquestiongroup',
            name='type',
            field=models.CharField(default='group', max_length=50),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='question_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='questionnaires.QuestionGroup'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='type',
            field=models.CharField(default='group', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalquestionnaire',
            name='version',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='version',
            field=models.BigIntegerField(),
        ),
    ]
